[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Configuración del puerto serial
monitor_speed = 115200

; Librerías
lib_deps = 
	bodmer/TFT_eSPI@^2.5.31
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	https://github.com/me-no-dev/AsyncTCP.git
	bblanchon/ArduinoJson@^6.21.3
	esp32-camera

; --- CONFIGURACIÓN DE LA PANTALLA ---
build_flags =
  -D BOARD_HAS_PSRAM
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_WIDTH=240
  -D TFT_HEIGHT=280
  -D TFT_MOSI=35
  -D TFT_SCLK=36
  -D TFT_CS=37
  -D TFT_DC=38
  -D TFT_RST=39
  -D TFT_BL=40
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SPI_FREQUENCY=27000000
  -D CGRAM_OFFSET=1
  -D TFT_INVERSION_ON=1
  -D TFT_RGB_ORDER=TFT_RGB
  -D USE_FSPI_PORT=1
